apiVersion: v1
kind: PersistentVolume
metadata:
   name: san-pv-10g
spec: 
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath: 
   path: /umniah/projects/html
  
